# Generated by Django 5.0 on 2023-12-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recruiters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('profession', models.CharField(max_length=30)),
                ('org', models.TextField()),
                ('role', models.CharField(max_length=20)),
                ('profile_pic', models.ImageField(upload_to='Profile_pics')),
                ('address', models.TimeField()),
                ('password', models.TextField()),
                ('about', models.TextField()),
            ],
        ),
    ]
