# Generated by Django 5.0 on 2023-12-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiters',
            name='address',
            field=models.TextField(),
        ),
    ]
