# Generated by Django 5.0 on 2023-12-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0002_alter_recruiters_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('time', models.IntegerField()),
                ('pay', models.IntegerField()),
                ('quantity', models.CharField(max_length=30)),
                ('rec', models.EmailField(max_length=254)),
                ('applied_emails', models.TextField()),
            ],
        ),
    ]
