# Generated by Django 5.0 on 2023-12-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0003_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doer', models.IntegerField()),
                ('action', models.TextField()),
                ('jobname', models.TextField()),
            ],
        ),
    ]
